CREATE TABLE IF NOT EXISTS departments (
    id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL,
    code        VARCHAR(20)     NOT NULL UNIQUE,
    description TEXT            DEFAULT NULL,
    manager_id  BIGINT UNSIGNED DEFAULT NULL,
    parent_id   BIGINT UNSIGNED DEFAULT NULL,
    color       VARCHAR(7)      DEFAULT '#6366f1',
    is_deleted  TINYINT(1)      NOT NULL DEFAULT 0,
    created_at  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
