CREATE TABLE IF NOT EXISTS employees (
    id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    employee_number VARCHAR(20)     NOT NULL UNIQUE,
    first_name      VARCHAR(60)     NOT NULL,
    last_name       VARCHAR(60)     NOT NULL,
    email           VARCHAR(255)    DEFAULT NULL,
    phone           VARCHAR(30)     DEFAULT NULL,
    title           VARCHAR(120)    DEFAULT NULL,
    department_id   BIGINT UNSIGNED DEFAULT NULL,
    manager_id      BIGINT UNSIGNED DEFAULT NULL,
    user_id         BIGINT UNSIGNED DEFAULT NULL,
    hire_date       DATE            DEFAULT NULL,
    birth_date      DATE            DEFAULT NULL,
    address         VARCHAR(255)    DEFAULT NULL,
    city            VARCHAR(100)    DEFAULT NULL,
    postal_code     VARCHAR(10)     DEFAULT NULL,
    country         VARCHAR(60)     DEFAULT 'Sverige',
    employment_type ENUM('full_time','part_time','consultant','intern') NOT NULL DEFAULT 'full_time',
    status          ENUM('active','on_leave','terminated') NOT NULL DEFAULT 'active',
    salary          DECIMAL(12,2)   DEFAULT NULL,
    notes           TEXT            DEFAULT NULL,
    is_deleted      TINYINT(1)      NOT NULL DEFAULT 0,
    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by      BIGINT UNSIGNED DEFAULT NULL,
    FOREIGN KEY (department_id) REFERENCES departments(id),
    FOREIGN KEY (manager_id)    REFERENCES employees(id),
    FOREIGN KEY (user_id)       REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
